version: "3.1"
nlu:
- intent: avoid_workout_boredom
  examples: |
    - How do I keep my workouts exciting?
- intent: weightlifting_shoes
  examples: |
    - What's the best footwear for cardio exercises?
- intent: gym_shoes
  examples: |
    - What shoes should I wear to the gym?
- intent: tone_or_bulk
  examples: |
    - How do I know if I need to tone or bulk?
- intent: six_pack_abs
  examples: |
    - What's the best way to get a six-pack?
- intent: overcome_weight_loss_plateau
  examples: |
    - What changes can I make to keep losing fat?
- intent: calculate_calories
  examples: |
    - Can you guide me on calorie counting?
- intent: post_workout_food
  examples: |
    - Can you recommend good post-exercise meals?
- intent: marathon_training
  examples: |
    - What's the best way to train for a marathon?
- intent: post_workout_rest
  examples: |
    - Can stretching reduce soreness?
- intent: bench_press_strength
  examples: |
    - What are tips for improving my bench press?
- intent: squat_mistakes
  examples: |
    - How do I squat without hurting my knees?
- intent: proper_squat
  examples: |
    - Can you explain the correct squat form?
- intent: exercise_mental_health
  examples: |
    - How does exercise improve mental health?
- intent: share_equipment
  examples: |
    - How do I politely request to use a machine someone's using?
- intent: fitness_apps_tracking
  examples: |
    - Can fitness apps help with tracking results?
- intent: workout_journal
  examples: |
    - Should I keep a journal of my gym sessions?
- intent: improve_running_pace
  examples: |
    - How do I increase my pace for long-distance runs?
- intent: running_speed
  examples: |
    - How do I improve my running speed?
- intent: hiit_vs_steady_state
  examples: |
    - Should I do HIIT or long cardio sessions?
- intent: cardio_duration_weight_loss
  examples: |
    - What's more effective for burning fat?
- intent: workout_time
  examples: |
    - Is there an ideal time for workouts?
- intent: workout_frequency
  examples: |
    - What's the recommended frequency for gym workouts?
- intent: lifting_gloves
  examples: |
    - Are lifting gloves helpful for grip?
    - Do I need gloves for weightlifting?
- intent: endurance_training
  examples: |
    - Can lifting weights help with endurance?
    - How do I last longer during cardio sessions?
- intent: strength_vs_hypertrophy
  examples: |
    - What's the difference between strength and hypertrophy training?
    - How does strength training compare to muscle growth workouts?
- intent: sleep_muscle_recovery
  examples: |
    - Does lack of sleep affect gym performance?
    - How important is sleep for muscle recovery?
- intent: proper_deadlift
  examples: |
    - How do I prevent back pain while deadlifting?
    - Can you guide me on deadlift technique?
- intent: improve_posture
  examples: |
    - How do I improve my posture?
    - What exercises help with better posture?
- intent: yoga_benefits
  examples: |
    - What are the benefits of yoga for gym-goers?
    - Can yoga improve my lifting performance?
- intent: anxiety_relief_workouts
  examples: |
    - What are good workouts for anxiety relief?
    - Are there specific exercises to calm the mind?
- intent: clean_gym_equipment
  examples: |
    - What's the proper way to clean gym equipment?
    - How do I sanitize equipment in the gym?
- intent: enjoyable_cardio
  examples: |
    - How do I keep cardio interesting?
    - What are fun ways to do cardio?
- intent: importance_rest_days
  examples: |
    - How important are rest days for progress?
    - Can I work out without taking breaks?
- intent: progressive_overload
  examples: |
    - What's the best approach for progressive overload?
    - What's the principle of progressive overload?
- intent: train_to_failure
  examples: |
    - Should I train to failure every set?
    - How often should I push myself to my limits?
- intent: hypertrophy_reps_sets
  examples: |
    - How many sets are ideal for gaining mass?
    - What's the optimal range of reps for muscle building?
- intent: burn_belly_fat
  examples: |
    - What are the best exercises to reduce belly fat?
    - Can you suggest workouts for fat loss?
- intent: water_intake_workout
  examples: |
    - How do I stay hydrated while working out?
    - How much water should I drink during a workout?
- intent: protein_shakes
  examples: |
    - Are protein shakes worth it for gym-goers?
    - Are protein shakes necessary for muscle growth?
- intent: gym_frequency
  examples: |
    - What's the best time to work out?
    - How many times a week should I go to the gym?
- intent: deadlift_belt
  examples: |
    - Is a belt necessary for deadlifts?
    - Should I use a belt for heavy lifting?
    - How do I properly wear a lifting belt?
- intent: improve_flexibility
  examples: |
    - Can you recommend stretches for tight muscles?
    - What are the best stretches for flexibility?
    - How do I get more flexible?
- intent: overcome_gym_anxiety
  examples: |
    - How do I deal with self-consciousness while working out?
    - What should I do if I feel intimidated at the gym?
    - How do I overcome gym anxiety?
- intent: workout_motivation
  examples: |
    - Can you give me tips to stay consistent?
    - How do I stay motivated to work out?
    - How do I keep pushing myself to exercise?
- intent: supersets
  examples: |
    - Should I try supersets for muscle definition?
    - What are supersets, and how do I perform them?
    - Can supersets help me save time at the gym?
- intent: drop_sets
  examples: |
    - Should I add drop sets to my routine?
    - Are drop sets effective for building muscle?
    - Should I use drop sets for muscle growth?
- intent: increase_strength
  examples: |
    - How do I increase my strength?
    - How can I increase strength over time?
    - How can I lift heavier weights over time?
- intent: build_muscle
  examples: |
    - How do I build muscle quickly?
    - Can you recommend exercises for gaining muscle?
    - What are the best tips for fast muscle growth?
- intent: pre_workout_food
  examples: |
    - Can you recommend a good pre-workout food?
    - What foods are ideal before exercising?
    - Should I eat before going to the gym?
- intent: beginner_gym_plan
  examples: |
    - Can you suggest a beginner-friendly gym plan?
    - Can you recommend a beginner-friendly gym class?
    - What exercises should a beginner do?
- intent: kettlebell_usage
  examples: |
    - How do I use kettlebells?
    - What's the best way to work out with kettlebells?
    - Can you show me kettlebell exercises?
- intent: dumbbell_usage
  examples: |
    - What's the right technique for dumbbell exercises?
    - How do I lift dumbbells correctly?
    - Can you explain proper dumbbell usage?
- intent: adjust_weights
  examples: |
    - How do I change the weights on a workout machine?
    - How do I adjust weights on a machine?
    - Can you guide me on adjusting gym machines?
- intent: treadmill_usage
  examples: |
    - Can you explain how to run on a treadmill?
    - How do I safely use the treadmill?
    - How do I use the treadmill?
- intent: warm_up
  examples: |
    - What are the best warm-up exercises?
    - How do I warm up before exercising?
    - What's the proper way to warm up?
- intent: personal_trainer
  examples: |
    - Do I need a personal trainer?
    - Can I work out without a trainer?
    - Is it worth hiring a personal trainer?
- intent: workout_recovery
  examples: |
    - How do I recover from a tough workout?
    - Should I take supplements for recovery?
    - What's the best way to recover after a workout?
    - What's the best way to deal with muscle soreness?
- intent: improve_stamina
  examples: |
    - Can you recommend tips to increase my energy levels?
    - How do I train for better stamina?
    - How do I improve my stamina?
    - What exercises can help boost endurance?
- intent: create_workout_plan
  examples: |
    - How should I plan my weekly workouts?
    - How do I create a workout plan?
    - What's the best workout routine for beginners?
    - What's the best way to organize my gym sessions?
- intent: injury_prevention
  examples: |
    - How do I avoid hurting myself during exercise?
    - What are the best tips for safe workouts?
    - How do I prevent injuries at the gym?
    - What are the most common gym injuries and how to avoid them?
    - How do I prevent gym injuries?
- intent: affirm
  examples: |
    - correct
    - that sounds good
    - indeed
    - of course
    - yes
- intent: deny
  examples: |
    - n
    - not really
    - don't like that
    - no
    - no way
    - never
- intent: cardio_vs_weights
  examples: |
    - What's better for fat loss: cardio or strength training?
    - Can weight training help with weight loss?
    - Is lifting weights better than cardio for losing fat?
    - Should I prioritize cardio over weights for fat loss?
    - Is cardio enough for weight loss?
    - Should I include strength training for fat loss?
    - What's the ideal duration of cardio for weight loss?
- intent: gym_essentials
  examples: |
    - How should I start my gym journey?
    - What should I bring to the gym?
    - I'm new to the gym, where should I begin?
    - What do I need for a gym session?
    - What essentials should I pack for the gym?
    - What's the first thing to do at the gym as a beginner?
    - What should I carry when I go to the gym?
- intent: goodbye
  examples: |
    - see you later
    - good night
    - cee you later
    - goodbye
    - good by
    - see you around
    - have a nice day
    - bye
    - bye bye
- intent: greet
  examples: |
    - hey dude
    - let's go
    - hey there
    - goodmorning
    - good evening
    - hello there
    - goodevening
    - hi
    - good afternoon
    - moin
    - hello
    - hey
- intent: mood_great
  examples: |
    - so perfect
    - feeling like a king
    - extremely good
    - I am amazing
    - so so perfect
    - so good
    - wonderful
    - amazing
    - I am feeling very good
    - great
    - perfect
    - I am great
    - I am going to save the world
- intent: mood_unhappy
  examples: |
    - sad
    - very sad
    - extremly sad
    - I am disappointed
    - so saad
    - I'm so sad
    - I don't feel very well
    - super sad
    - so sad
    - I am sad
    - unhappy
    - not very good
    - not good
- intent: recommend_muscle_group_exercise
  examples: |
    - What can I do to train my [chest](muscle_group)
    - I want to train my [chest](muscle_group)
    - What can I do to train my [core](muscle_group)
    - Which exercise should I do to train my [back](muscle_group)
    - I want to train my [abs](muscle_group)
    - What's a good exercise for my [core](muscle_group)?
    - Which exercise should I do to train my [leg](muscle_group)
    - What's a good exercise for my [shoulder](muscle_group)?
    - I want to train my [leg](muscle_group)
    - Which exercise should I do to train my [abs](muscle_group)
    - I want to train my [shoulder](muscle_group)
    - What can I do to train my [back](muscle_group)
    - Which exercise should I do to train my [shoulder](muscle_group)
    - What's a good exercise for my [abs](muscle_group)?
    - What can I do to train my [leg](muscle_group)
    - I want to train my [back](muscle_group)
    - Which exercise should I do to train my [core](muscle_group)
    - Which exercise should I do to train my [chest](muscle_group)
    - What can I do to train my [shoulder](muscle_group)
    - I want to train my [core](muscle_group)
    - What can I do to train my [abs](muscle_group)
    - What's a good exercise for my [leg](muscle_group)?
    - What's a good exercise for my [back](muscle_group)?
